name: Format review

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  review:
    name: Review formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Restore CI Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}

      - name: Install Dependencies
        if: ${{ !steps.cache.outputs.cache-hit }}
        run: bun ci

      - name: Run ESLint
        run: bunx eslint .
